spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kingmaker
    username: postgres
    password: 123654
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # 仅开发阶段使用！上线前必须改为 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect